project_id = "AhmedZ"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54332
shadow_port = 54330
major_version = 17

[functions.create-admin-user]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-admin-user/index.ts"

[functions.create-admin-customer]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-admin-customer/index.ts"

[functions.convert-party-to-customer]
enabled = true
verify_jwt = false
entrypoint = "./functions/convert-party-to-customer/index.ts"

[functions.delete-admin-user]
enabled = true
verify_jwt = false
entrypoint = "./functions/delete-admin-user/index.ts"

[functions.reset-admin-password]
enabled = true
verify_jwt = false
entrypoint = "./functions/reset-admin-password/index.ts"
